export const HR_ROUTES = {
    DASHBOARD: '/hr/dashboard',
    EMPLOYEES: '/hr/employees',
    EMPLOYEES_NEW: '/hr/employees/new',
    EMPLOYEES_DETAIL: (id: string) => `/hr/employees/${id}`,
    EMPLOYEES_EDIT: (id: string) => `/hr/employees/${id}/edit`,
    ASSIGNMENTS: '/hr/assignments',
    ASSIGNMENTS_NEW: '/hr/assignments/new',
    ASSIGNMENTS_DETAIL: (id: string) => `/hr/assignments/${id}`,
    ASSIGNMENTS_EDIT: (id: string) => `/hr/assignments/${id}/edit`,
    PROFILE: '/hr/profile',
    CHANGE_PASSWORD: '/hr/change-password',
    UNIVERSITY_OVERVIEW: '/hr/university-overview',
    ORG_STRUCTURE: '/hr/org-structure',
    ORG_TREE: '/hr/org-tree',
    ORG_TREE_DETAIL: (id: string) => `/hr/org-tree/${id}`,
    ORG_TREE_EMPLOYEES: (id: string) => `/hr/org-tree/${id}/employees`,
    FACULTY: '/hr/faculty',
    QUALIFICATIONS: '/hr/qualifications',
    EMPLOYEE_QUALIFICATIONS: '/hr/employee-qualifications',
    EMPLOYMENTS: '/hr/employments',
    PERFORMANCE_REVIEWS: '/hr/performance-reviews',
    ACADEMIC_TITLES: '/hr/academic-titles',
    EMPLOYEE_ACADEMIC_TITLES: '/hr/employee-academic-titles',
    TRAININGS: '/hr/trainings',
    EMPLOYEE_TRAININGS: '/hr/employee-trainings',
    EMPLOYEE_LOGS: '/hr/employee-logs',
    ROLES: '/hr/roles',
    PERMISSIONS: '/hr/permissions',
    ROLE_PERMISSIONS: '/hr/role-permissions',
    USER_ROLES: '/hr/user-roles',
    REPORTS: '/hr/reports',
};

export const ORG_ROUTES = {
    DASHBOARD: '/org/dashboard',
    TREE: '/org/tree',
    DIAGRAM: '/org/diagram',
    REPORTS: '/org/reports',
    CONFIG: '/org/config',
    HISTORY: '/org/unit/create/audit',
    UNIT: '/org/unit',
    UNIT_DETAIL: (id: string) => `/org/unit/${id}`,
    UNIT_CREATE: {
        REVIEW: '/org/unit/review',
        AUDIT: '/org/unit/create/audit',
    },
};

export const API_ROUTES = {
    ACADEMIC: {
        HISTORY: '/api/academic/history',
    },
    HR: {
        EMPLOYEES: '/api/hr/employees',
        EMPLOYEES_BY_ID: (id: string) => `/api/hr/employees/${id}`,
        USERS: '/api/hr/users',
        USERS_BY_ID: (id: string) => `/api/hr/users/${id}`,
        ASSIGNMENTS: '/api/hr/assignments',
        ASSIGNMENTS_BY_ID: (id: string) => `/api/hr/assignments/${id}`,
        ORG_UNITS_MINI: '/api/hr/org-units',
        QUALIFICATIONS: '/api/hr/qualifications',
        QUALIFICATIONS_BY_ID: (id: string) => `/api/hr/qualifications/${id}`,
        EMPLOYEE_QUALIFICATIONS: '/api/hr/employee-qualifications',
        EMPLOYEE_QUALIFICATIONS_BY_ID: (id: string) => `/api/hr/employee-qualifications/${id}`,
        EMPLOYMENTS: '/api/hr/employments',
        EMPLOYMENTS_BY_ID: (id: string) => `/api/hr/employments/${id}`,
        PERFORMANCE_REVIEWS: '/api/hr/performance-reviews',
        PERFORMANCE_REVIEWS_BY_ID: (id: string) => `/api/hr/performance-reviews/${id}`,
        ACADEMIC_TITLES: '/api/hr/academic-titles',
        ACADEMIC_TITLES_BY_ID: (id: string) => `/api/hr/academic-titles/${id}`,
        EMPLOYEE_ACADEMIC_TITLES: '/api/hr/employee-academic-titles',
        EMPLOYEE_ACADEMIC_TITLES_BY_ID: (id: string) => `/api/hr/employee-academic-titles/${id}`,
        TRAININGS: '/api/hr/trainings',
        TRAININGS_BY_ID: (id: string) => `/api/hr/trainings/${id}`,
        EMPLOYEE_TRAININGS: '/api/hr/employee-trainings',
        EMPLOYEE_TRAININGS_BY_ID: (id: string) => `/api/hr/employee-trainings/${id}`,
        EMPLOYEE_LOGS: '/api/hr/employee-logs',
        ORG_UNITS_MINI: '/api/hr/org-units',
        ROLES: '/api/hr/roles',
        ROLES_BY_ID: (id: string) => `/api/hr/roles/${id}`,
        PERMISSIONS: '/api/hr/permissions',
        PERMISSIONS_BY_ID: (id: string) => `/api/hr/permissions/${id}`,
        ROLE_PERMISSIONS: '/api/hr/role-permissions',
        ROLE_PERMISSIONS_BY_ID: (id: string) => `/api/hr/role-permissions/${id}`,
        USER_ROLES: '/api/hr/user-roles',
        USER_ROLES_BY_ID: (id: string) => `/api/hr/user-roles/${id}`,
        ME: '/api/hr/me',
        POSITIONS: '/api/hr/positions',
    },
    ORG: {
        STATS: '/api/org/stats',
        UNITS: '/api/org/units',
        UNITS_BY_ID: (id: string) => `/api/org/units/${id}`,
        UNITS_AUDIT: '/api/org/units/audit',
        UNITS_HISTORY: (id: string) => `/api/org/units/${id}/history`,
        UNITS_STATUS: (id: string) => `/api/org/units/${id}/status`,
        INITIAL_UNITS: '/api/org/initial-units',
        HISTORY: '/api/org/history',
        HISTORY_BY_ID: (id: string) => `/api/org/history/${id}`,
        UNIT_RELATIONS: '/api/org/unit-relations',
        UNIT_RELATIONS_BY_ID: (id: string) => `/api/org/unit-relations/${id}`,
        ASSIGNMENTS: '/api/org/assignments',
        ASSIGNMENTS_BY_ID: (id: string) => `/api/org/assignments/${id}`,
        TYPES: '/api/org/types',
        STATUSES: '/api/org/statuses',
        STATUSES_BY_ID: (id: string) => `/api/org/statuses/${id}`,
        KPI: {
            HEADCOUNT: '/api/org/kpi/headcount',
        },
    },
    TMS: {
        FACULTIES: '/api/tms/faculties',

        // programs
        PROGRAMS: '/api/tms/programs',
        PROGRAMS_BY_ID: (id: string) => `/api/tms/programs/${id}`,
        PROGRAMS_BLOCKS: '/api/tms/programs/blocks',
        PROGRAMS_BLOCKS_BY_ID: (id: string, type?: string) => type ? `/api/tms/programs/blocks/${id}?type=${type}` : `/api/tms/programs/blocks/${id}`,
        PROGRAM_COURSE_MAP: '/api/tms/program-course-map',
        PROGRAM_COURSE_MAP_BY_ID: (id: string) => `/api/tms/program-course-map/${id}`,
        PROGRAM_GROUPS: '/api/tms/program-groups',
        PROGRAM_GROUPS_BY_ID: (id: string) => `/api/tms/program-groups/${id}`,

        PROGRAMS_LIST: '/api/tms/programs/list',
        PROGRAMS_APPLY_FRAMEWORK: '/api/tms/programs/apply-default-framework',
        PROGRAMS_COPY_STRUCTURE: '/api/tms/programs/copy-structure',
        PROGRAMS_STATS: '/api/tms/programs/stats',
        PROGRAM_BLOCK_TEMPLATES: '/api/tms/program-blocks', // block templates
        PROGRAM_COURSE_MAP_BULK: '/api/tms/program-course-map/bulk',

        // courses
        COURSES: '/api/tms/courses',
        COURSES_BY_ID: (id: string) => `/api/tms/courses/${id}`,
        COURSES_SYLLABUS: (id: string) => `/api/tms/courses/${id}/syllabus`,
        COURSES_VERSIONS: (id: string) => `/api/tms/courses/${id}/versions`,
        COURSES_PREREQUISITES: (id: string, prereqId: string) => `/api/tms/courses/${id}/prerequisites/${prereqId}`,
        COURSES_STATS: '/api/tms/courses/stats',
        COURSES_LIST: '/api/tms/courses/list',

        // majors
        MAJORS: '/api/tms/majors',
        MAJORS_BY_ID: (id: string) => `/api/tms/majors/${id}`,
        MAJORS_ORG_UNITS: '/api/tms/majors/org-units',
        MAJORS_STATS: '/api/tms/majors/stats',

        // cohorts
        COHORTS: '/api/cohorts',
        COHORTS_BY_ID: (id: string) => `/api/cohorts/${id}`,
        COHORTS_STATISTICS: '/api/cohorts/statistics',
        COHORTS_STATS: '/api/tms/cohorts/stats',

        // curriculums - chưa dùng
        CURRICULUM: '/api/tms/curriculum',
        CURRICULUM_BY_ID: (id: string) => `/api/tms/curriculum/${id}`,

        // add
        REPORTS_OVERVIEW: '/api/tms/reports/overview',
        DASHBOARD_STATS: '/api/tms/dashboard/stats',
        REVIEW: '/api/tms/review',
    },
    UPLOAD: '/api/upload',
};
